### ISSUE TITLE
push metypeset docker image

### ISSUE THREAD

**Issue by de-code** [elifesciences/metypeset-docker#1]
This is based on [cermine-docker](https://github.com/elifesciences/cermine-docker). One difference is that it also adds an API server to call the executable. That is why the _image tag_ should be related to this repository and not just the version / commit of _meTypeset_.

Could you please review and push the image?

**Comment by giorgiosironi** [comment]
Building PRs, but also `develop` pipeline at https://alfred.elifesciences.org/job/image/job/image-metypeset/

**Comment by giorgiosironi** [comment]
Switched https://alfred.elifesciences.org/job/image/job/image-metypeset/ to `develop` rather than the test branch.

**Comment by giorgiosironi** [comment]
Can we close this now?

**Comment by de-code** [comment]
Should there I see an image in https://hub.docker.com/u/elifesciences/ or do I need to trigger it separately?

**Comment by giorgiosironi** [comment]
It's there, but on page 2: https://hub.docker.com/u/elifesciences/?page=2 and https://hub.docker.com/r/elifesciences/metypeset/

**Comment by de-code** [comment]
Apologies, got used to being sorted by activity.
